version: '3.3'
services:
 web:
   build:
     context: ./
   volumes:
     - .:/src
   command: supervisor -e '.' index.js
   ports:
     - "3000:3000"
   depends_on:
     - db
 db:
   image: mysql
   restart: always
   env_file:
     - ./.env
   ports:
     - "3308:3306"
   volumes:
     - "./db:/var/lib/test/"
   command: --default-authentication-plugin=mysql_native_password --innodb-flush-method=O_DIRECT --innodb-use-native-aio=0 --ignore-db-dir=lost+found --ignore-db-dir=tmp --ignore-db-dir=mysql --ignore-db-dir=performance_schema --ignore-db-dir=information_schema --skip-innodb-read-only-compressed --skip-host-cache --skip-name-resolve --innodb-buffer-pool-size=256M --innodb-log-file-size=1G --innodb-file-per-table=1 --innodb-open-files=10000 --innodb-print-all-deadlocks=1 --innodb-buffer-pool-instances=16 --innodb-page-cleaners=8 --innodb-thread-concurrency=0 --innodb-read-io-threads=16 --innodb-write-io-threads=16 --log-bin=mysql-bin --binlog-format=ROW --server-id=1
 phpmyadmin:
   image: phpmyadmin/phpmyadmin:latest
   restart: always
   env_file:
     - ./.env
   ports:
     - "8081:80"

